micronaut:
  application:
    name: pixServer
    #--> lembrar de mudar o uuid para binary 16 no mysql
datasources:
  default:
    url: jdbc:mysql://localhost:3306/pix?useTimezone=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
    schema-generate: CREATE_DROP
    dialect: MYSQL
jpa.default.properties.hibernate.hbm2ddl.auto: update

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep_alive_time: 1h
    max_inbound-message-size: 1024

itau.contas.url: 'http://localhost:9091'
bcb.contas.url: 'http://localhost:8082'